#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
import subprocess
import requests
import yaml

from i3pystatus import Status, IntervalModule
from i3pystatus.iinet import IINet
from i3pystatus.updates import pacman, cower
from i3pystatus.mail import imap

with open('/home/max/.secrets/i3pystatus.yml') as f:
    secrets = yaml.load(f)
    
wifi_card = 'wlp4s0'

status = Status()


__author__ = 'chestm007'

status.register(
    "updates",
    format="Updates: {count}",
    format_no_updates="",
    on_leftclick="termite --geometry=1200x600 --title=updates -e "
                 "'pacaur --needed --noconfirm --noedit -Syu'",
    backends=[pacman.Pacman(), cower.Cower()]
)

status.register(
    "clock",
    format="%d/%m  %H:%M:%S",
    color='#C678DD',
    interval=0.5,
    on_leftclick="/usr/bin/gsimplecal"
)

status.register(
    "temp",
    color='#78EAF2',
    file="/sys/class/hwmon/hwmon3/temp1_input",
    format='Card 2:{temp}',
    interval=0.5
)

status.register(
    "temp",
    color='#78EAF2',
    file="/sys/class/hwmon/hwmon2/temp1_input",
    format='Card 1:{temp}',
    interval=0.5
)

status.register(
    "temp",
    color='#78EAF2',
    file="/sys/class/hwmon/hwmon0/temp1_input",
    format='CPU:{temp}',
    interval=0.5
)

status.register(
    "pulseaudio",
    color_unmuted='#98C379',
    color_muted='#E06C75',
    format_muted='[muted]',
    format="VOL {volume}%"
)

status.register(
    "network",
    interface='enp5s0',
    color_up="#8AE234",
    color_down="#EF2929",
    format_up="{v4cidr} {interface}",
    format_down="NO WIFI"
)


status.register(
    "cpu_usage",
    on_leftclick="termite --title=htop -e 'htop'",
    format="CPU {usage}%",
    dynamic_color=True,
    start_color='#11AA11',
    end_color='#AA1111'
)

status.register(
    'bitcoin',
)

status.register(
    "mail",
    hide_if_null=False,
    backends=[
        imap.IMAP(
            account='Hotmail',
            host="imap-mail.outlook.com", port=993, ssl=True,
            username='chestm007@hotmail.com',
            password=secrets['mail']['chestm007.hotmail.com']
        ),
        imap.IMAP(
            account='Instac',
            host='imap.gmail.com', port=993, ssl=True,
            password=secrets['mail']['max.instaclustr.com'],
            username='max@instaclustr.com'
        )
    ]
)

status.run()
