#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
import subprocess
import requests
import yaml

from i3pystatus import Status, IntervalModule
from i3pystatus.iinet import IINet
from i3pystatus.updates import pacman, cower
from i3pystatus.mail import imap
from i3pystatus.weather import weathercom
from i3pystatus.calendar import google

with open('/home/max/.secrets/i3pystatus.yml') as f:
    secrets = yaml.load(f)
    
with open('/home/max/.config/i3/i3pystatus-conf.yml') as f:
    my_colors = yaml.load(f)
    

wifi_card = 'wlp4s0'

status = Status(logfile='/home/max/.i3pystatus.log')


__author__ = 'chestm007'

status.register(
    'plexstatus',
    color=my_colors['normal'],
    apikey=secrets['plex']['token'],
    address='192.168.1.2',
    stream_divider=' | ',
    format='{product}({streamer_os}) - {title}'
)

status.register(
    'pagerduty',
    color=my_colors['normal'],
    api_key=secrets['pagerduty']['token'],
    user_id='PIG20GL'
)

status.register(
    'pomodoro',
    break_duration=3,
    pomodoro_duration=60,
    long_break_duration=15,
    color={
        'running': my_colors['normal'],
        'stopped': my_colors['normal'],
        'break': my_colors['urgent']
    }
)

status.register(
    'calendar',
    color=my_colors['normal'],
    format='{title} - {humanize_remaining}',
    backend=google.Google(credentials_json='/home/max/Downloads/credentials.json',
                          credential_path='/home/max/Downloads/token.json')
)

status.run()
