#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
import subprocess
import requests
import yaml

from i3pystatus import Status, IntervalModule
from i3pystatus.iinet import IINet
from i3pystatus.updates import pacman, cower
from i3pystatus.mail import imap
from i3pystatus.weather import weathercom

with open('/home/max/.secrets/i3pystatus.yml') as f:
    secrets = yaml.load(f)

with open('/home/max/.config/i3/i3pystatus-conf.yml') as f:
    my_colors = yaml.load(f)

    
wifi_card = 'wlp4s0'

status = Status(logfile='/home/max/.i3pystatus.log')


__author__ = 'chestm007'

status.register(
    'net_speed',
    color=my_colors['normal'],
    interval=3600,
    format="↓{speed_down:.1f}{down_units} ↑{speed_up:.1f}{up_units}"
)

status.register(
    'bitcoin',
    color=my_colors['normal'],
)

status.register(
    'weather',
    online_interval=300,
    offline_interval=5,
    color=my_colors['normal'],
    #colorize=True,
    format='{condition} {current_temp}{temp_unit}[ {icon}][ Hi: {high_temp}][ Lo: {low_temp}][ {update_error}]',
    hints=dict(
        markup='pango',
    ),
    backend=weathercom.Weathercom(
        location_code='ASAC0002:1:AS',
        units='metric',
    )
)

status.register(
    'github',
    colors={
        'good': my_colors['normal'],
        'minor': my_colors['urgent'],
        'major': my_colors['fail'],
    },
    access_token=secrets['github']['token'],
    notify_status=True,
    notify_unread=True
)
status.run()
