#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
from datetime import timedelta, datetime

from i3pystatus import Status, IntervalModule

from i3pystatus.calendar import google
import yaml

with open('/home/max/.secrets/i3pystatus.yml') as f:
    secrets = yaml.load(f)

with open('/home/max/.config/i3/i3pystatus-conf.yml') as f:
    my_colors = yaml.load(f)


wifi_card = 'wlp4s0'

status = Status()


__author__ = 'chestm007'


#status.register(
#    "temp",
#    color=my_colors['normal'],
#    file="/sys/class/hwmon/hwmon0/temp1_input",
#    interval=0.1,
#    format='{temp:.1f} °C'
#)
#
#status.register(
#    "cpu_freq",
#    color=my_colors['normal'],
#    interval=0.1,
#    format="{avgg}Ghz"
#)

status.run()
