#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
from datetime import timedelta, datetime

from i3pystatus import Status, IntervalModule

from i3pystatus.calendar import google
import yaml

with open('/home/max/.secrets/i3pystatus.yml') as f:
    secrets = yaml.load(f)

with open('/home/max/.config/i3/i3pystatus-conf.yml') as f:
    my_colors = yaml.load(f)


wifi_card = 'wlp4s0'

status = Status()


__author__ = 'chestm007'


status.register(
    "temp",
    color=my_colors['normal'],
    file="/sys/class/hwmon/hwmon0/temp1_input",
    interval=0.1,
    format='{temp:.1f} °C'
)

status.register(
    "cpu_freq",
    color=my_colors['normal'],
    interval=0.1,
    format="{avgg}Ghz"
)

status.register(
    "disk",
    color=my_colors['normal'],
    path="/",
    on_leftclick="pcmanfm",
    format="Root {avail}GB"
)

status.register(
    "disk",
    color=my_colors['normal'],
    path="/mnt/games",
    on_leftclick="pcmanfm",
    format="Games {avail}GB"
)

status.register(
    'iinet',
    start_color=my_colors['normal'],
    end_color=my_colors['normal'],
    username=secrets.get('iinet').get('username'),
    password=secrets.get('iinet').get('password'),
    format='vdsl2+ {used}GB'
)

circle_repo_status_map = {'success': '<span color="{}">passed</span>'.format(my_colors['success']),
                          'started': '<span color="{}">started</span>'.format(my_colors['normal']),
                          'failed': '<span color="{}">failed</span>'.format(my_colors['fail'])}
circle_token = secrets.get('circleci').get('token')

repos = dict(
    Pyalsi='chestm007/pyalsi',
    Slack='chestm007/py_slack_terminal',
    LTRiing='chestm007/linux_thermaltake_riing',
    AUR='chestm007/my-aur-packages',
)

for name, repo_slug in repos.items():
    status.register(
        'circleci',
        format=name + '/{repo_status} [({last_build_started})]',
        color=my_colors['normal'],
        repo_status_map=circle_repo_status_map,
        hints={'markup': 'pango'},
        circleci_token=circle_token,
        repo_slug=repo_slug,
    )

status.run()
