#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
import subprocess
import requests
import yaml

from i3pystatus import Status, IntervalModule
from i3pystatus.iinet import IINet
from i3pystatus.updates import pacman, cower
from i3pystatus.mail import imap

with open('/home/max/.secrets/i3pystatus.yml') as f:
    secrets = yaml.load(f)
with open('/home/max/.config/i3/i3pystatus-conf.yml') as f:
    my_colors = yaml.load(f)
    
wifi_card = 'wlp4s0'

status = Status(logfile='/home/max/.i3pystatus.log')


__author__ = 'chestm007'

status.register(
    "updates",
    format="Updates: {count}",
    color=my_colors['normal'],
    color_no_updates=my_colors['normal'],
    color_working=my_colors['normal'],
    format_no_updates="Up to Date.",
    on_leftclick="termite --geometry=1200x600 --title=updates -e "
                 "'pacaur --needed --noconfirm --noedit -Syu'",
    backends=[pacman.Pacman(), cower.Cower()]
)

status.register(
    "clock",
    color=my_colors['normal'],
    format="%d/%m  %H:%M:%S",
    interval=0.5,
    on_leftclick="/usr/bin/gsimplecal"
)

status.register(
    'amdgpu',
    color=my_colors['normal'],
    card=0,
    interval=0.1,
    format='Gpu0: {temp:>3.0f} {sclk:>7} {gpu_usage:>3}% {fan_speed:>4}rpm'
)

status.register(
    "pulseaudio",
    color_unmuted=my_colors['normal'],
    color_muted='#E06C75',
    format_muted='[muted]',
    format="VOL {volume:>3}%"
)

status.register(
    "network",
    interface='enp5s0',
    hints = {'markup': 'pango'},
    separate_color = True,
    color_up=my_colors['normal'],
    color_down=my_colors['urgent'],
    format_up="{v4cidr} {network_graph_recv} {bytes_recv:>10}/s {rx_tot:>7}",
    graph_direction='right-to-left',
    auto_units=True,
    ignore_interfaces=['lo', 'docker0'],
    detached_down=False,
    interval=1,
    round_size=2,
    sent_limit=1024 * 3,
    recv_limit=1024 * 9,
    dynamic_color=False
)

status.register(
    'cpu_usage_graph',
    color=my_colors['normal'],
    direction='right-to-left',
    on_leftclick="terminator --title=htop -e 'htop'",
)

status.register(
    "mail",
    hide_if_null=False,
    color=my_colors['normal'],
    color_unread=my_colors['normal'],
    backends=[
        imap.IMAP(
            account='Hotmail', ssl=True,
            host="imap-mail.outlook.com", port=993,
            username='chestm007@hotmail.com',
            password=secrets['mail']['chestm007.hotmail.com']
        ),
        imap.IMAP(
            account='Instac',
            host='imap.gmail.com', port=993, ssl=True,
            password=secrets['mail']['max.instaclustr.com'],
            username='max@instaclustr.com'
        )
    ]
)

status.run()
