#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
import subprocess
import requests
import yaml

from i3pystatus import Status, IntervalModule
from i3pystatus.iinet import IINet
from i3pystatus.updates import pacman, cower
from i3pystatus.mail import imap

with open('/home/max/.secrets/i3pystatus.yml') as f:
    secrets = yaml.load(f)

with open('/home/max/.config/i3/i3pystatus-conf.yml') as f:
    my_colors = yaml.load(f)

    
wifi_card = 'wlp4s0'

status = Status(logfile='/home/max/.i3pystatus.log')


__author__ = 'chestm007'


status.register(
    'deluge',
    color=my_colors['normal'],
    host='192.168.1.2',
    username=secrets['deluge']['username'],
    password=secrets['deluge']['password'],
    format='⛆{num_torrents} ✇{free_space_bytes} ⇓{download_rate}s ⇑{upload_rate}s ⟱{total_download}',
    on_leftclick='deluge',
    interval=10
)

status.run()
