tasks:
  Movies:
    exists_movie: /mnt/raid/Movies/
    imdb_lookup: yes
    html:
      url: https://thepiratebay.org/top/207
      title_from: url
      links_re: [ magnet ]
    proper_movies: yes
    regexp:
      accept:
        - '2017'
        - '2016'
        - '2015'
        - '2014'
        - 1080p
        - BRRip
        - DvdRip
        - BluRay
      reject:
        - x265
        - h265
        - WebRip
        - WEBRip
        - 720p
        - Hindi
    template: 
      - deluge_settings
      - piratebay_manipulate

  TvShows:
    html:
      url: https://thepiratebay.org/search/{{series_name}}/0/99/0
      title_from: url
      links_re: [ magnet ]
    exists_series: /mnt/raid/TvShows/
    series:
      - The Big Bang Theory:
          set:
            movedone: "/mnt/raid/TvShows/Big Bang Theory/Season {{series_season}}/"
      - Shooter:
          set:
            movedone: "/mnt/raid/TvShows/Shooter/Season {{series_season}}"
      - Silicon Valley:
          set:
            movedone: "/mnt/raid/TvShows/SiliconValley/Season {{series_season}}/"
      - Mr Robot:
          set:
            movedone: "/mnt/raid/TvShows/mr robot/Season{{series_season}}/"
      - Game Of Thrones:
          set:
            movedone: "/mnt/raid/TvShows/Game of thrones/Season{{series_season}}/"
      - Vikings:
          set:
            movedone: "/mnt/raid/TvShows/Vikings/Season{{series_season}}/"
      - Heartland:
          set:
            movedone: "/mnt/raid/TvShows/Heartland/Season{{series_season}}/"
      - Wanted:
          set:
            movedone: "/mnt/raid/TvShows/Wanted/Season{{series_season}}/"
      - This is us:
          set:
            movedone: "/mnt/raid/TvShows/ThisIsUs/Season{{series_season}}/"
      - Breaking Bad:
          set:
            movedone: "/mnt/raid/TvShows/BreakingBad/Season{{series_season}}/"
      - Archer:
          set:
            movedone: "/mnt/raid/TvShows/Archer/Season{{series_season}}/"
      - Orphan Black:
          set:
            movedone: "/mnt/raid/TvShows/OrphanBlack/Season{{series_season}}/"
      - Continuum:
          set:
            movedone: "/mnt/raid/TvShows/Continuum/Season{{series_season}}/"
      - Narcos:
          set:
            movedone: "/mnt/raid/TvShows/Narcos/Season{{series_season}}/"
      - House of Cards:
          set:
            movedone: "/mnt/raid/TvShows/HouseOfCards/Season{{series_season}}/"
      - Stranger Things:
          set:
            movedone: "/mnt/raid/TvShows/StrangerThings/Season{{series_season}}/"
      - Wire:
          set:
            html:
              url: https://thepiratebay.org/search/{{series_name}}/0/99/0
            movedone: "/mnt/raid/TvShows/Wire/Season{{series_season}}/"
    template: 
      - deluge_settings
      - piratebay_manipulate

templates:
  deluge_settings:
    deluge:
      username: localclient
      password: b0a09b057e2a2251d78d9bd11344fd249b7277da
      path: /mnt/raid/Movies/
  piratebay_manipulate:
    manipulate:
      - title:
          from: url
          extract: '&dn=(.*?)&tr=udp'
      - title:
          replace:
            regexp: '\+'
            format: ' '

schedules:
  - tasks: '*'
    interval:
      minutes: 30
